spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footwithme?useSSL=false&serverTimezone=UTC
    username: root
    password: 5497

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect